FROM python:3
WORKDIR /usr/src/app

RUN pip install Django
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./python ./

EXPOSE 8000
CMD ["python", "./ignore/manage.py", "runserver", "0.0.0.0:8000"]