FROM ranadeeppolavarapu/nginx-http3:latest
RUN apk add certbot certbot-nginx
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN mkdir /etc/letsencrypt
RUN mkdir /etc/nginx/conf.d
RUN mkdir /var/www
COPY nginx.conf /etc/nginx/
WORKDIR /usr/src/app
COPY ./python/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
